In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [39]:
data_dir = "../Data/Raw/"
data_2016 = pd.read_csv(data_dir+"roc_2016.csv")
data_2016.head()

,storyid,storytitle,sentence1,sentence2,sentence3,sentence4,sentence5
0,9a51198e-96f1-42c3-b09d-a3e1e067d803,Overweight Kid,Dan's parents were overweight.,Dan was overweight as well.,The doctors told his parents it was unhealthy.,His parents understood and decided to make a c...,They got themselves and Dan on a diet.
1,617e7ada-3878-488d-bd56-40695b91f053,The Bike Accident,Carrie had just learned how to ride a bike.,She didn't have a bike of her own.,Carrie would sneak rides on her sister's bike.,She got nervous on a hill and crashed into a w...,The bike frame bent and Carrie got a deep gash...
2,79b0da1f-e460-4173-ba58-8c9e2553c53a,Beach,Morgan enjoyed long walks on the beach.,She and her boyfriend decided to go for a long...,"After walking for over a mile, something happe...",Morgan decided to propose to her boyfriend.,Her boyfriend was upset he didn't propose to h...
3,d173b7de-4611-4cdf-934c-912834755e41,The bad customer.,Jane was working at a diner.,"Suddenly, a customer barged up to the counter.",He began yelling about how long his food was t...,Jane didn't know how to react.,"Luckily, her coworker intervened and calmed th..."
4,af0fd5a4-de36-47ba-8aa2-e99d10986d7a,Being Patient,I was talking to my crush today.,She continued to complain about guys flirting ...,I decided to agree with what she says and list...,"After I got home, I got a text from her.",She asked if we can hang out tomorrow.

In [40]:
data_2017 = pd.read_csv(data_dir+"roc_2017.csv")
data_2017.head()

,storyid,storytitle,sentence1,sentence2,sentence3,sentence4,sentence5
0,8bbe6d11-1e2e-413c-bf81-eaea05f4f1bd,David Drops the Weight,David noticed he had put on a lot of weight re...,He examined his habits to try and figure out t...,He realized he'd been eating too much fast foo...,He stopped going to burger places and started ...,"After a few weeks, he started to feel much bet..."
1,0beabab2-fb49-460e-a6e6-f35a202e3348,Frustration,Tom had a very short temper.,One day a guest made him very angry.,He punched a hole in the wall of his house.,Tom's guest became afraid and left quickly.,Tom sat on his couch filled with regret about ...
2,87da1a22-df0b-410c-b186-439700b70ba6,Marcus Buys Khakis,Marcus needed clothing for a business casual e...,All of his clothes were either too formal or t...,He decided to buy a pair of khakis.,The pair he bought fit him perfectly.,Marcus was happy to have the right clothes for...
3,2d16bcd6-692a-4fc0-8e7c-4a6f81d9efa9,Different Opinions,Bobby thought Bill should buy a trailer and ha...,Bill thought a truck would be better for what ...,Bobby pointed out two vehicles were much more ...,Bill was set in his ways with conventional thi...,He ended up buying the truck he wanted despite...
4,c71bb23b-7731-4233-8298-76ba6886cee1,Overcoming shortcomings,John was a pastor with a very bad memory.,He tried to memorize his sermons many days in ...,He decided to learn to sing to overcome his ha...,He then made all his sermons into music and sa...,His congregation was delighted and so was he.

In [41]:
print("Stories 2016: %i" %len(data_2016))
print("Stories 2017: %i" %len(data_2017))

Stories 2016: 45496
Stories 2017: 52665

In [42]:
data = data_2016.append(data_2017)
print("Stories Total: %i" %len(data))
data.head()

Stories Total: 98161

,storyid,storytitle,sentence1,sentence2,sentence3,sentence4,sentence5
0,9a51198e-96f1-42c3-b09d-a3e1e067d803,Overweight Kid,Dan's parents were overweight.,Dan was overweight as well.,The doctors told his parents it was unhealthy.,His parents understood and decided to make a c...,They got themselves and Dan on a diet.
1,617e7ada-3878-488d-bd56-40695b91f053,The Bike Accident,Carrie had just learned how to ride a bike.,She didn't have a bike of her own.,Carrie would sneak rides on her sister's bike.,She got nervous on a hill and crashed into a w...,The bike frame bent and Carrie got a deep gash...
2,79b0da1f-e460-4173-ba58-8c9e2553c53a,Beach,Morgan enjoyed long walks on the beach.,She and her boyfriend decided to go for a long...,"After walking for over a mile, something happe...",Morgan decided to propose to her boyfriend.,Her boyfriend was upset he didn't propose to h...
3,d173b7de-4611-4cdf-934c-912834755e41,The bad customer.,Jane was working at a diner.,"Suddenly, a customer barged up to the counter.",He began yelling about how long his food was t...,Jane didn't know how to react.,"Luckily, her coworker intervened and calmed th..."
4,af0fd5a4-de36-47ba-8aa2-e99d10986d7a,Being Patient,I was talking to my crush today.,She continued to complain about guys flirting ...,I decided to agree with what she says and list...,"After I got home, I got a text from her.",She asked if we can hang out tomorrow.

In [43]:
X_train = pd.DataFrame(columns=["Input"])
y_train = pd.DataFrame(columns=["Correct Ending"])
X_train["Input"] = data["sentence1"]+" "+data["sentence3"]+" "+data["sentence4"]
X_train.head()

                                               Input
0  Dan's parents were overweight. The doctors tol...
1  Carrie had just learned how to ride a bike. Ca...
2  Morgan enjoyed long walks on the beach. After ...
3  Jane was working at a diner. He began yelling ...
4  I was talking to my crush today. I decided to ...

In [44]:
X_train["Input"] = "<S> "+X_train["Input"]+" </S>"
X_train.head(5)

                                               Input
0  <S> Dan's parents were overweight. The doctors...
1  <S> Carrie had just learned how to ride a bike...
2  <S> Morgan enjoyed long walks on the beach. Af...
3  <S> Jane was working at a diner. He began yell...
4  <S> I was talking to my crush today. I decided...

In [45]:
len(max(X_train['Input']))

137

In [46]:
y_train["Correct Ending"] = data["sentence5"]
y_train["Correct Ending"] = "<S> "+y_train["Correct Ending"]+" </S>"
y_train.head()

                                      Correct Ending
0    <S> They got themselves and Dan on a diet. </S>
1  <S> The bike frame bent and Carrie got a deep ...
2  <S> Her boyfriend was upset he didn't propose ...
3  <S> Luckily, her coworker intervened and calme...
4    <S> She asked if we can hang out tomorrow. </S>

In [19]:
len(max(y_train['Correct Ending']))

43

In [47]:
X_train_series = X_train["Input"]
y_train_series = y_train["Correct Ending"]

In [48]:
print(X_train["Input"].str.len().max(), y_train["Correct Ending"].str.len().max())

223 102

In [49]:
np.savetxt(r'../Data/Untokenized/train.src.en', X_train.values, fmt="%s")
np.savetxt(r'../Data/Untokenized/train.tgt.en', y_train.values, fmt="%s")

### Validation Data

In [23]:
validation_data = pd.read_csv(data_dir+'validation.csv')
print("Validation Data: %i" %len(validation_data))
validation_data.head()

Validation Data: 1871

,InputStoryid,InputSentence1,InputSentence2,InputSentence3,InputSentence4,RandomFifthSentenceQuiz1,RandomFifthSentenceQuiz2,AnswerRightEnding
0,138d5bfb-05cc-41e3-bf2c-fa85ebad14e2,Rick grew up in a troubled household.,"He never found good support in family, and tur...",It wasn't long before Rick got shot in a robbery.,The incident caused him to turn a new leaf.,He is happy now.,He joined a gang.,1
1,bff9f820-9605-4875-b9af-fe6f14d04256,Laverne needs to prepare something for her fri...,She decides to bake a batch of brownies.,She chooses a recipe and follows it closely.,Laverne tests one of the brownies to make sure...,The brownies are so delicious Laverne eats two...,Laverne doesn't go to her friend's party.,1
2,e8f628d5-9f97-40ed-8611-fc0e774673c4,Sarah had been dreaming of visiting Europe for...,She had finally saved enough for the trip.,She landed in Spain and traveled east across t...,She didn't like how different everything was.,Sarah then decided to move to Europe.,Sarah decided that she preferred her home over...,2
3,f5226bfe-9f26-4377-b05f-3d9568dbdec1,Gina was worried the cookie dough in the tube ...,She was very happy to find she was wrong.,The cookies from the tube were as good as from...,Gina intended to only eat 2 cookies and save t...,Gina liked the cookies so much she ate them al...,Gina gave the cookies away at her church.,1
4,69ac9b05-b956-402f-9fff-1f926ef9176b,It was my final performance in marching band.,I was playing the snare drum in the band.,We played Thriller and Radar Love.,The performance was flawless.,I was very proud of my performance.,I was very ashamed of my performance.,1

In [24]:
X_valid = pd.DataFrame(columns=["Input"])
y_valid = pd.DataFrame(columns=["Correct Ending"])
X_valid["Input"] = validation_data["InputSentence1"]+" "+validation_data["InputSentence3"]+" "+validation_data["InputSentence4"]
X_valid.head()

                                               Input
0  Rick grew up in a troubled household. It wasn'...
1  Laverne needs to prepare something for her fri...
2  Sarah had been dreaming of visiting Europe for...
3  Gina was worried the cookie dough in the tube ...
4  It was  my final performance in marching band....

In [26]:
X_valid["Input"] = "<S> "+X_valid["Input"]+" </S>"
X_valid.head()

                                               Input
0  <S> Rick grew up in a troubled household. It w...
1  <S> Laverne needs to prepare something for her...
2  <S> Sarah had been dreaming of visiting Europe...
3  <S> Gina was worried the cookie dough in the t...
4  <S> It was  my final performance in marching b...

In [27]:
correct_endings = []
for row in range(len(validation_data)):
    if (int(validation_data.iloc[row]["AnswerRightEnding"]) == 1):
        correct_endings.append(validation_data.iloc[row]["RandomFifthSentenceQuiz1"])
    elif (int(validation_data.iloc[row]["AnswerRightEnding"]) == 2):
        correct_endings.append(validation_data.iloc[row]["RandomFifthSentenceQuiz2"])
y_valid["Correct Ending"] = correct_endings
y_valid["Correct Ending"] = "<S> "+y_valid["Correct Ending"]+" </S>"
print(len(y_valid))
y_valid.head()

1871

                                      Correct Ending
0                          <S> He is happy now. </S>
1  <S> The brownies are so delicious Laverne eats...
2  <S> Sarah decided that she preferred her home ...
3  <S> Gina liked the cookies so much she ate the...
4       <S> I was very proud of my performance. </S>

In [28]:
np.savetxt(r'../Data/Untokenized/valid.src.en', X_valid.values, fmt="%s")
np.savetxt(r'../Data/Untokenized/valid.tgt.en', y_valid.values, fmt="%s")

### Test Data

In [29]:
test_data = pd.read_csv(data_dir+"test.csv")
test_data.head()

,InputStoryid,InputSentence1,InputSentence2,InputSentence3,InputSentence4,RandomFifthSentenceQuiz1,RandomFifthSentenceQuiz2,AnswerRightEnding
0,b929f263-1dcd-4a0b-b267-5d5ff2fe65bb,My friends all love to go to the club to dance.,They think it's a lot of fun and always invite.,I finally decided to tag along last Saturday.,I danced terribly and broke a friend's toe.,My friends decided to keep inviting me out as ...,"The next weekend, I was asked to please stay h...",2
1,7cbbc0af-bcce-4f56-871d-963f9bb6a99d,I tried going to the park the other day.,The weather seemed nice enough for a walk.,Within minutes of getting there I started snee...,My eyes were watery and it was hard to breathe.,My allergies were too bad and I had to go back...,It reminded me of how much I loved spring flow...,1
2,4745d627-be9b-45f2-ad92-99c82cc83f85,Avery was married with children.,She was tired of her boring life.,"One day, she decided to meet up with an old bo...",She made poor decisions that night and was unf...,Avery thought her children would be happy with...,Avery regretted what she did the next day.,2
3,6bc5a855-3a02-454c-8d8b-4428b1864f95,Josh loved when his mom baked apple pie.,He hated how he always had to wait until after...,So he decided this time he would sneak a piece...,The eggs his mom used must have been bad though.,Josh thought that the pie was delicious.,Josh got sick.,2
4,2f74e81d-957b-4541-9e66-59e5eaa6aef1,John was writing lyrics for his new album.,He started experiencing writer's block.,He tried to force himself to write but it woul...,"He took a walk, hung out with some friends, an...",He felt inspiration and then went back home to...,John then got an idea for his painting.,1

In [32]:
X_test = pd.DataFrame(columns=["Input"])
y_test_1 = pd.DataFrame(columns=["Ending1"])
y_test_2 = pd.DataFrame(columns=["Ending2"])
X_test["Input"] = test_data["InputSentence1"]+" "+test_data["InputSentence3"]+" "+test_data["InputSentence4"]
X_test.head()

                                               Input
0  My friends all love to go to the club to dance...
1  I tried going to the park the other day. Withi...
2  Avery was married with children. One day, she ...
3  Josh loved when his mom baked apple pie. So he...
4  John was writing lyrics for his new album. He ...

In [33]:
X_test["Input"] = "<S> "+X_test["Input"]+" </S>"
X_test.head()

                                               Input
0  <S> My friends all love to go to the club to d...
1  <S> I tried going to the park the other day. W...
2  <S> Avery was married with children. One day, ...
3  <S> Josh loved when his mom baked apple pie. S...
4  <S> John was writing lyrics for his new album....

In [34]:
y_test_1["Ending1"] = test_data["RandomFifthSentenceQuiz1"]
y_test_1["Ending1"] = "<S> "+y_test_1["Ending1"]+" </S>"
y_test_1.head()

                                             Ending1
0  <S> My friends decided to keep inviting me out...
1  <S> My allergies were too bad and I had to go ...
2  <S> Avery thought her children would be happy ...
3  <S> Josh thought that the pie was delicious. </S>
4  <S> He felt inspiration and then went back hom...

In [35]:
y_test_2["Ending2"] = test_data["RandomFifthSentenceQuiz2"]
y_test_2["Ending2"] = "<S> "+y_test_2["Ending2"]+" </S>"
y_test_2.head()

                                             Ending2
0  <S> The next weekend, I was asked to please st...
1  <S> It reminded me of how much I loved spring ...
2  <S> Avery regretted what she did the next day....
3                            <S> Josh got sick. </S>
4   <S> John then got an idea for his painting. </S>

In [36]:
y_test_true = pd.DataFrame(columns=["Correct Ending"])
correct_endings = []
for row in range(len(test_data)):
    if (int(test_data.iloc[row]["AnswerRightEnding"]) == 1):
        correct_endings.append(test_data.iloc[row]["RandomFifthSentenceQuiz1"])
    elif (int(test_data.iloc[row]["AnswerRightEnding"]) == 2):
        correct_endings.append(test_data.iloc[row]["RandomFifthSentenceQuiz2"])
y_test_true["Correct Ending"] = correct_endings
y_test_true["Correct Ending"] = "<S> "+y_test_true["Correct Ending"]+" </S>"
y_test_true.head()

                                      Correct Ending
0  <S> The next weekend, I was asked to please st...
1  <S> My allergies were too bad and I had to go ...
2  <S> Avery regretted what she did the next day....
3                            <S> Josh got sick. </S>
4  <S> He felt inspiration and then went back hom...

In [38]:
np.savetxt(r'../Data/Untokenized/test.src.en', X_test.values, fmt="%s")

In [37]:
np.savetxt(r'../Data/Untokenized/test_ending_1.src.en', y_test_1.values, fmt="%s")
np.savetxt(r'../Data/Untokenized/test_ending_2.src.en', y_test_2.values, fmt="%s")
np.savetxt(r'../Data/Untokenized/test.tgt.en', y_test_true.values, fmt="%s")